"""04.09.2024 20:02

Revision ID: 38847a818bc9
Revises: 2087fff4a572
Create Date: 2024-09-04 20:02:20.167830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38847a818bc9'
down_revision: Union[str, None] = '2087fff4a572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'total_score')
    op.drop_column('user', 'total_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('total_game', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('total_score', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
