"""04.09.2024 20:04

Revision ID: 687b383a818f
Revises: 38847a818bc9
Create Date: 2024-09-04 20:04:38.280745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687b383a818f'
down_revision: Union[str, None] = '38847a818bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('game_id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_time', sa.String(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('player_score', sa.Integer(), nullable=False),
    sa.Column('player_kill', sa.Integer(), nullable=False),
    sa.Column('player_shot', sa.Integer(), nullable=False),
    sa.Column('all_shot', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('game_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
