"""24.09.2024 09:46

Revision ID: 7baaa428463e
Revises: 21ab4504ef5b
Create Date: 2024-09-24 09:46:28.758566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7baaa428463e'
down_revision: Union[str, None] = '21ab4504ef5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verify', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verify')
    # ### end Alembic commands ###
