"""24.09.2024 09:35

Revision ID: 9e7a1a9874e4
Revises: 88e1adc1ac2e
Create Date: 2024-09-24 09:35:10.959211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e7a1a9874e4'
down_revision: Union[str, None] = '88e1adc1ac2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('email_verify', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verify')
    op.drop_column('user', 'email')
    op.create_table('game',
    sa.Column('game_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_time', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('game_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('player_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_kill', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('player_shot', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('all_shot', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], name='game_user_id_fkey'),
    sa.PrimaryKeyConstraint('game_id', name='game_pkey')
    )
    # ### end Alembic commands ###
