"""08.09.2024 17:29

Revision ID: e04f1155fd83
Revises: a86a72172365
Create Date: 2024-09-08 17:29:08.406552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e04f1155fd83'
down_revision: Union[str, None] = 'a86a72172365'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('desktop_status', sa.Boolean(), nullable=False))
    op.alter_column('session', 'fk_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session', 'fk_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('session', 'desktop_status')
    # ### end Alembic commands ###
